"""Add password_hash column to employee

Revision ID: 35ae24415411
Revises: 
Create Date: 2024-09-18 13:09:32.531598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ae24415411'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
        batch_op.alter_column('profession',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])
        batch_op.drop_column('total_amount')
        batch_op.drop_column('remaining_amount')
        batch_op.drop_column('paid_amount')


    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('national_id',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('national_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_amount', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('remaining_amount', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('total_amount', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.alter_column('profession',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('employee_id')
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###
